### ISSUE TITLE
测试公平性的修正建议

### ISSUE THREAD

**Issue by YangruiEmma** [rpcxio/rpcx-benchmark#13]
感谢鸟窝老师继续发布 RPC 框架测试报告，但既然对外发布还是希望能保持公平、清晰的原则，关于协议、序列化、测试方式、RPC 场景四个方面希望能补充说明和调整：
1. 协议
消息协议、传输协议对 RPC 性能会产生影响，Protobuf 只是序列化部分，这两者是不同的。就协议来说，gRPC 基于 HTTP2，相对其他框架处理会更加复杂，当然都是用 Protobuf 可以作对比，但因为协议上的差异，测试报告中应该说明。Kitex 的压测对比是有区分 Protobuf 和 gRPC 的。

2. 序列化
序列化对 RPC 产生的性能影响不用多说，既然这个测试报告都用 Protobuf，那序列化也应该保持一致，但这个测试里只有 Kitex 用 Protobuf 官方的生成代码，其他框架都是用的是 [gogo/protobuf](https://github.com/gogo/protobuf)，这一点在报告中并未说明。
gogo/protobuf 是一个很优秀的项目，但 Kitex 考虑到长期迭代的问题没有使用 gogo/protobuf，因为该库目前是无人维护状态。Kitex 在 Protobuf 编码性能上也有优化，后续会开源 [cloudwego/fastpb](https://github.com/cloudwego/fastpb)。

3. 测试方式
相对去年对 Kitex 测试反馈的连接池策略问题，感谢鸟窝老师予以采纳，这次测试使用了连接多路复用。Kitex 的连接多路复用大部分场景只需要1个连接即可，默认也是一个连接，单实例压测配置较多连接反而会带来性能劣化。rpcx和arpc需要10个client发压提升吞吐，而Kitex连接多路复用可以用更少的资源达到吞吐和延迟表现较好的状态。如果只对比10个client或多个连接发压作为结果也不合理，实际的应用场景中也是共享一个client而不是多个。

4. RPC 场景
所谓的 RPC 场景，服务端是有业务逻辑处理的，不是简单的 echo，arpc 在服务端的同步处理方式不适应用于大部分 RPC 场景，这个之前也有讨论，这次鸟窝老师的压测中对服务端增加了 delay 参数应该也是对此有所考虑，如果设置delay=1ms，就能从结果看出差异。对齐 RPC 场景应该改为异步方式，配置见 https://github.com/cloudwego/kitex-benchmark/blob/main/protobuf/arpc/main.go#L59

以上，如果大家有不同意见，欢迎讨论~ 关于 2、3 如果没有疑议，我可以提交pr修改

**Comment by smallnest** [comment]
感谢 @YangruiEmma  提出的建议。
我觉得你的四点建议都是对的，欢迎提供pr, 我用来修正和重测。

关于第一点， 传输采用的各自框架的传输方式，arpc服务治理的功能少一些，所以这一方面可能会有一些优势，因为不需要处理复杂的服务治理的功能。我会更新一下文章，把这个说清楚。 rpcx使用的传输协议rpcx自带的协议，payload采用protobuf。arpc的传输也是自研的，kitex传输是thrift?还是自定义的？

第四点我虽然加了delay,但是没有测试，完整的测试也应该加上，期望我有时间也做一个delay的测试。 另外希望能再加一个业务CPU敏感场景的测试。

anyway, 谢谢你的建议，欢迎你提供pr和指正，让我们把国内的框架一同做的更好

**Comment by YangruiEmma** [comment]
@smallnest 感谢鸟窝老师回复，#14 是关于2、3的修改

**Comment by lesismal** [comment]
@YangruiEmma 4中，arpc的代码其实已经有了一个 -a 选项，设置为true就是异步响应的。arpc 1.2.10已经把异步响应作为默认参数。我本地笔记本跑了下测试，这个cpu消耗的测试，arpc同步响应19.1w，异步16.6w，rpcx 14.6w，kite 11.1w。我gitalk也有留言，在kitex-benchmark中的kitex-mux确实数据很好，希望大佬有空给解答下做了哪些优化
