### ISSUE TITLE
希望加个-limit参数判断是否执行限流，以及性能上限测试方法优化

### ISSUE THREAD

**Issue by lesismal** [rpcxio/rpcx-benchmark#2]
## 增加-limit主要是考虑按业务场景区分：
1. DB/IO等慢消耗业务（常见的CURD类业务）
2. CPU消耗为主的业务（比如游戏，web也有一些直接取进程内内存缓存的场景）

现在的限流版本相当于只覆盖了1的场景

## 性能上限测试方法优化

[老仓库](https://github.com/rpcx-ecosystem/rpcx-benchmark)的benchmark方法我觉得也可以进一步完善下：

1. 多个连接
2. 每个连接多个协程
3. 每个协程不固定请求数量，一直请求，直到达到目标qps/tps值终止请求然后计算

这种应该可以较大程度压出上限

**Comment by smallnest** [comment]
> 2.CPU消耗为主的业务（比如游戏，web也有一些直接取进程内内存缓存的场景）
这个可以执行一个特定的耗 CPU的任务，比如我在go-web-framework-benchmark中实现了一个区块链计算hash的方法。专门用来测试CPU敏感的场景。

老仓库的代码可以忽略了，我准备achived，以后主要看这个项目的benchmark。

那个tarsgo输出日志的问题你可以提交一个pull request,修复一下tarsgo的测试用例。

thanks

**Comment by lesismal** [comment]
> > 2.CPU消耗为主的业务（比如游戏，web也有一些直接取进程内内存缓存的场景）
> > 这个可以执行一个特定的耗 CPU的任务，比如我在go-web-framework-benchmark中实现了一个区块链计算hash的方法。专门用来测试CPU敏感的场景。
> 
> 老仓库的代码可以忽略了，我准备achived，以后主要看这个项目的benchmark。
> 
> 那个tarsgo输出日志的问题你可以提交一个pull request,修复一下tarsgo的测试用例。
> 
> thanks

OK, 已PR
