### ISSUE TITLE
依赖冲突

### ISSUE THREAD

**Issue by Dup4** [rpcxio/rpcx-benchmark#7]
- `rpcx` 依赖 `thrift v0.14.0`，而 `kitex` 依赖 `thrift v0.13.0`。
- 如果不通过一些特殊的方法，无法在同一个 module 里依赖另一个 module 的两个版本。
---
- 是否可以考虑在每个 `benchmark` 中新起一个 module，而不是将所有框架都整在一个 module 里。
- 但是 `stats.go` 中引用了 `rpcx` 中的日志模块，这部分需要改动一下。
- 这样对以后增加新的框架的 benchmark，扩展性也是比较好的。
- 至少不需要通过在 `go.mod` 中添加 replace，而跑其它框架的时候又需要注释掉 `replace` 这种操作了。

**Comment by smallnest** [comment]
是的。周末重构一下，每个框架一个module,避免冲突
