### ISSUE TITLE
疑问:  arpc server的启动参数

### ISSUE THREAD

**Issue by rfyiamcool** [rpcxio/rpcx-benchmark#8]
arpc server在启动时有加入 async 异步参数么？ 这个参数会决定在处理handle时，是否go func()来处理。

[https://github.com/rpcxio/rpcx-benchmark/blob/master/arpc/server/arpc_server.go#L42](https://github.com/rpcxio/rpcx-benchmark/blob/master/arpc/server/arpc_server.go#L42)

**Comment by smallnest** [comment]
启动的时候是默认的，所以async应该为false。
今天有时间我把async设置为true看看性能

**Comment by smallnest** [comment]
arpc async=true时
```

**Comment by smallnest** [comment]
async=true时
```
2021/08/04 13:44:07 stats.go:38: INFO : received requests_OK : 10000000
2021/08/04 13:44:07 stats.go:42: INFO : throughput  (TPS)    : 153652

2021/08/04 13:44:07 stats.go:45: INFO : mean: 649034 ns, median: 393546 ns, max: 37598590 ns, min: 37294 ns, p99.9: 7418359 ns
```

async=false时
```
2021/08/04 13:45:11 stats.go:42: INFO : throughput  (TPS)    : 230755

2021/08/04 13:45:11 stats.go:45: INFO : mean: 432028 ns, median: 299556 ns, max: 22766880 ns, min: 30295 ns, p99.9: 6668660 ns
```

async=false时反而性能会更好

**Comment by lesismal** [comment]
> async=false时反而性能会更好

其实最佳性能是根据不同的业务路由选择sync还是async，这个测试中因为只有一个路由，所以就用了全局的设置。
如果需要定制性能最佳化可以这样：
```golang
isAsync := false
svr.Handler.Handle("/fast", onFastMethod, isAsync)
isAsync := true
svr.Handler.Handle("/slow", onSlowMethod, isAsync)
```

或者在handler中自行判断是否需要异步响应：
```golang
func onMethod(ctx *arpc.Context) {
	if slow {
		go func() { // 当然，这里也可以用户自行选择协程池组件来提高性能以及避免大量慢路由请求造成协程爆炸
			// ...
			ctx.Write(...)
		}()
	} else {
		//
		ctx.Write(...)
	}
}
```

最近给 arpc 支持了 pool ，默认不开启，则只是创建 Context/Message/Buffer 这些对象时使用 Pool.Get、无放回，如果开启，则会放回，Message 加了引用计数，广播时候需要用户 Retain/Release。
在我的新笔记本上（5800x 8c16t）测试，pool 开启后性能又提升了一些。但因为跟各位不同硬件测试得到的，所以还不确定是否真的提升了，但至少内存/GC重度的场景应该会更稳定。

**Comment by lesismal** [comment]
之前在我的低配笔记本4c8t的VM中测试时，arpc各项指标最优，七夕我老婆送了我台新笔记本，R9000P 5800H 32g，loopback 跑确实是 rpcx 指标要高，但是像字节同学提到的一样，如果考虑 cpu 占用，rpcx 的占用要高出一大截，计算单位 cpu 消耗对应的 tps 时 rpcx 仍不占优。

另外，最近给 arpc 加上了 obj 和 buffer 的 pool 选项，开启后综合性能又提升了一截，刚刚 PR 了下 pool 版本：https://github.com/rpcxio/rpcx-benchmark/pull/11

rpcx-benchmark 对比了下pool 和 非 pool 版本

- 环境
> ubuntu server 20.04
> 5800h 8c16t, 32g

| 框架&&版本 |  c+s cpu 占用 | tps |
|---|---|---|
| arpc no pool | 1000-1100% | 29-30w |
| rpcx | 1400-1600% | 31-32w |
| arpc pool | 1100-1200% | 36-38w|

pool 版本 kitex-benchmark 的结果：
![image](https://user-images.githubusercontent.com/40462947/129697698-0cf1a32f-7b96-442f-8874-6cd0f50b3176.png)
![image](https://user-images.githubusercontent.com/40462947/129697790-a7fd174a-8137-4bb7-9ed5-6d476426fb52.png)
![image](https://user-images.githubusercontent.com/40462947/129697844-6ca4570b-1fe3-474a-89f3-95ff35964a7b.png)
![image](https://user-images.githubusercontent.com/40462947/129697889-aca407fd-1320-49ff-addd-485eb48af62a.png)
![image](https://user-images.githubusercontent.com/40462947/129697945-50699b43-5d93-425b-abcc-5d7f32f087ed.png)
![image](https://user-images.githubusercontent.com/40462947/129697986-d99a8c04-5392-4e6c-b06d-f0eb10204d07.png)
